#!/usr/bin/env ansible-playbook
- hosts: demo
  gather_facts: false
  tasks:
    - name: Overprint test
      command: "false"
      retries: 5
      delay: 1
      register: result
      until: result.rc == 0
