#!/usr/bin/env ansible-playbook
- hosts: locals
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: python3
  tasks:
    - name: Echo
      command: "echo foo"

    - name: Command
      command: "true"
      retries: 4
      delay: 1
      register: result
      until: "false"
      ignore_errors: true

    - name: Retries
      command: "true"
      retries: 9
      delay: 1
      register: result
      changed_when: false
      until: result.attempts == canary

    - name: Loop
      debug:
        msg: Hello world!
      with_sequence: count=2
