#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Rich test
      command: "false"
      retries: 5
      delay: 1
      register: result
      until: result.rc == 0
