#!/usr/bin/env ansible-playbook
---
- name: Generate example hosts
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: python3
  tasks:
    - add_host:
        name: "host{{ item }}"
        groups:
          - locals
        canary: "{{ item }}"
      loop: "{{ range(1, 6) }}"
      loop_control:
        label: "host{{ item }}"

- name: Demonstrate moreati.rich.rich callback
  hosts: locals
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: python3
    canary: "{{ inventory_hostname[4:] }}"
  tasks:
    - name: Echo
      command: "echo foo"

    - name: Command
      command: "true"
      retries: 4
      delay: 1
      register: result
      until: "false"
      ignore_errors: true

    - name: Retries
      command: "true"
      retries: 9
      delay: 1
      register: result
      changed_when: false
      until: result.attempts == canary|int

    - name: Loop
      debug:
        msg: Hello world!
      with_sequence: count=2
